---
- name: Base configuration for all servers
  hosts: all
  become: true
  roles:
    - common

- name: Configure the database server
  hosts: database
  become: true
  roles:
    - database

- name: Configure the webapp servers
  hosts: webservers
  become: true
  roles:
    - webserver

- name: Configure the load balancer
  hosts: loadbalancer
  become: true
  roles:
    - loadbalancer
